ALTER TABLE "users" ADD COLUMN "activeFrameId" TEXT;

ALTER TABLE "gifts" ADD COLUMN "nameAr" TEXT NOT NULL DEFAULT '';
ALTER TABLE "gifts" ADD COLUMN "coinsValue" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "gifts" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
