import 'roulette_engine.dart';

class RouletteStrings {
  final bool ar;
  const RouletteStrings(this.ar);
  String text(String key) => (ar ? _arabic : _english)[key] ?? key;
  String get footer => ar
      ? 'يعمل بعملات سمافوكس — لا تُحوَّل إلى نقود ولا تُسحب، ولا توجد جوائز مالية حقيقية.'
      : 'Runs on SamaFox coins — they do not convert to money or withdraw; no real-money prizes.';
  String round(int n) => ar ? 'الجولة: $n' : 'Round: $n';
  String seconds(int s) => ar ? '$s ث' : '${s}s';
  String winning(int n) => '${text('winningNumber')}: $n ${color(n)}';
  String color(int n) => switch (rouletteColor(n)) {
        RouletteColor.green => text('green'),
        RouletteColor.red => text('red'),
        RouletteColor.black => text('black'),
      };

  /// Readable name of a bet key, for the history and accessibility labels.
  String bet(String key) {
    final b = rouletteBet(key);
    if (b == null) return key;
    final nums = b.numbers.join('·');
    return switch (b.type) {
      'straight' => '${text('straight')} $nums',
      'split' => '${text('split')} $nums',
      'street' => '${text('street')} $nums',
      'corner' => '${text('corner')} $nums',
      'sixLine' => '${text('sixLine')} $nums',
      'firstFour' => '${text('firstFour')} 0·1·2·3',
      _ => text(key),
    };
  }

  static const _english = {
    'title': 'ROULETTE',
    'ranking': 'Ranking',
    'players': 'Players',
    'totalBet': 'Total Bet',
    'myTotalBet': 'My total bet',
    'balance': 'Balance',
    'recharge': 'Recharge',
    'new': 'NEW',
    'help': 'Help',
    'paytable': 'Paytable',
    'history': 'History',
    'settings': 'Settings',
    'sound': 'Sound',
    'motion': 'Motion',
    'language': 'Language',
    'arabic': 'العربية',
    'english': 'English',
    'close': 'Close',
    'back': 'Back',
    'retry': 'Try again',
    'loading': 'Loading table…',
    'clear': 'Clear',
    'undo': 'Undo',
    'rebet': 'Rebet',
    'betting': 'Place your bets',
    'closing': 'Bets closed — wait for the result',
    'spinning': 'Spinning…',
    'result': 'Result',
    'winningNumber': 'Winning number',
    'youWon': 'You won',
    'noWin': 'No win this round',
    'green': 'green',
    'red': 'RED',
    'black': 'BLACK',
    'odd': 'ODD',
    'even': 'EVEN',
    'low': '1–18',
    'high': '19–36',
    'dozen1': '1st 12',
    'dozen2': '2nd 12',
    'dozen3': '3rd 12',
    'column1': '2:1',
    'column2': '2:1',
    'column3': '2:1',
    'straight': 'Number',
    'split': 'Split',
    'street': 'Street',
    'corner': 'Corner',
    'sixLine': 'Six line',
    'firstFour': 'First four',
    'payout': 'Pays (bet included)',
    'covers': 'Numbers',
    'emptyHistory': 'No rounds yet.',
    'emptyRanking': 'No winners yet today — be the first!',
    'emptyPlayers': 'No bets on the table yet this round.',
    'todayNet': 'Your net today',
    'bestWin': 'Best win today',
    'noNews': 'No news right now.',
    'statsNote': 'Past results do not predict the next round.',
    'lastResults': 'Last results',
    'rules':
        'One table for everyone. While the timer runs, pick a chip and tap the table: a number, the line between two numbers (split), the corner of four, the outer edge of a row (street) or between two rows (six line), or any outside box. When betting closes the wheel spins and the ball lands on one number from 0 to 36.',
    'rulesZero':
        'Zero is green: it loses every outside bet (red/black, odd/even, 1–18/19–36, dozens, columns) and wins only bets that include 0.',
    'rulesPay':
        'Payouts include your bet and are set so the game runs on the shared prize pool; they are lower than a casino table. Every number is equally likely.',
    'rulesFair':
        'Each round commits to a hidden seed (its hash is shown while you bet) and reveals it with the result: the number is sha256(seed:round) mod 37.',
    'seedHash': 'Round seed (hash)',
    'seed': 'Revealed seed',
    'BETTING_CLOSED': 'Bets are closed — wait for the next round.',
    'INSUFFICIENT_COINS': 'Not enough coins.',
    'BAD_TARGET': 'That is not a betting spot.',
    'BAD_AMOUNT': 'Pick a chip first.',
    'MAX_BET': 'That spot is at its maximum.',
    'BET_TOO_HIGH': 'You reached the round limit.',
    'NO_PREVIOUS': 'No previous bet to repeat.',
    'NO_BET': 'Nothing to undo.',
    'GAME_DISABLED': 'The game is paused right now.',
    'DAILY_WIN_CAP': 'You reached today\'s win cap in this game.',
    'PRIZE_POOL_LOW': 'The prize pool cannot cover this bet right now.',
    'NETWORK': 'Connection lost. Try again.',
    'FAILED': 'Something went wrong. Try again.',
    'error': 'Could not load the table. Check your connection.',
  };

  static const _arabic = {
    'title': 'الروليت',
    'ranking': 'الترتيب',
    'players': 'اللاعبون',
    'totalBet': 'إجمالي الرهانات',
    'myTotalBet': 'إجمالي رهاني',
    'balance': 'الرصيد',
    'recharge': 'إعادة الشحن',
    'new': 'جديد',
    'help': 'المساعدة',
    'paytable': 'جدول الدفع',
    'history': 'السجل',
    'settings': 'الإعدادات',
    'sound': 'الصوت',
    'motion': 'الحركة',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'English',
    'close': 'إغلاق',
    'back': 'رجوع',
    'retry': 'حاول مرة أخرى',
    'loading': 'جاري تحميل الطاولة…',
    'clear': 'مسح',
    'undo': 'تراجع',
    'rebet': 'إعادة الرهان',
    'betting': 'ضع رهانك',
    'closing': 'الرهانات مغلقة — انتظر النتيجة',
    'spinning': 'جاري الدوران...',
    'result': 'النتيجة',
    'winningNumber': 'الرقم الفائز',
    'youWon': 'ربحت',
    'noWin': 'لا فوز هذه الجولة',
    'green': 'أخضر',
    'red': 'أحمر',
    'black': 'أسود',
    'odd': 'فردي',
    'even': 'زوجي',
    'low': '1–18',
    'high': '19–36',
    'dozen1': 'الـ12 الأولى',
    'dozen2': 'الـ12 الثانية',
    'dozen3': 'الـ12 الثالثة',
    'column1': '2:1',
    'column2': '2:1',
    'column3': '2:1',
    'straight': 'رقم',
    'split': 'رقمان',
    'street': 'صف',
    'corner': 'زاوية',
    'sixLine': 'صفّان',
    'firstFour': 'الأربعة الأولى',
    'payout': 'الدفع (شامل الرهان)',
    'covers': 'الأرقام',
    'emptyHistory': 'لا توجد جولات بعد.',
    'emptyRanking': 'لا يوجد فائزون اليوم بعد — كن الأول!',
    'emptyPlayers': 'لا توجد رهانات على الطاولة في هذه الجولة بعد.',
    'todayNet': 'صافي ربحك اليوم',
    'bestWin': 'أكبر فوز اليوم',
    'noNews': 'لا توجد أخبار جديدة الآن.',
    'statsNote': 'الإحصائيات السابقة لا تتنبأ بنتيجة الجولة القادمة.',
    'lastResults': 'آخر النتائج',
    'rules':
        'طاولة واحدة للجميع. أثناء العدّاد اختر شريحة واضغط على الطاولة: رقم، أو الخط بين رقمين، أو زاوية أربعة أرقام، أو الحافة الخارجية لصف (3 أرقام) أو بين صفّين (6 أرقام)، أو أي خانة خارجية. عند إغلاق الرهانات تدور العجلة وتستقر الكرة على رقم واحد من 0 إلى 36.',
    'rulesZero':
        'الصفر أخضر: يخسر كل الرهانات الخارجية (أحمر/أسود، فردي/زوجي، 1–18/19–36، الدزينات، الأعمدة) ولا يفوز إلا بالرهانات التي تشمل 0.',
    'rulesPay':
        'الدفع يشمل رهانك، ومحدد بحيث تعمل اللعبة على صندوق الجوائز المشترك؛ وهو أقل من طاولة الكازينو. كل الأرقام لها نفس الاحتمال.',
    'rulesFair':
        'كل جولة تلتزم ببذرة مخفية (تظهر مشفّرة أثناء الرهان) وتُكشف مع النتيجة: الرقم = sha256(البذرة:الجولة) mod 37.',
    'seedHash': 'بذرة الجولة (مشفّرة)',
    'seed': 'البذرة المكشوفة',
    'BETTING_CLOSED': 'الرهانات مغلقة — انتظر الجولة القادمة.',
    'INSUFFICIENT_COINS': 'رصيدك لا يكفي.',
    'BAD_TARGET': 'هذه ليست خانة رهان.',
    'BAD_AMOUNT': 'اختر شريحة أولًا.',
    'MAX_BET': 'هذه الخانة وصلت للحد الأقصى.',
    'BET_TOO_HIGH': 'وصلت للحد الأقصى للجولة.',
    'NO_PREVIOUS': 'لا يوجد رهان سابق لإعادته.',
    'NO_BET': 'لا يوجد ما تتراجع عنه.',
    'GAME_DISABLED': 'اللعبة متوقفة حاليًا.',
    'DAILY_WIN_CAP': 'وصلت للحد اليومي لمكاسبك في هذه اللعبة.',
    'PRIZE_POOL_LOW': 'صندوق الجوائز لا يغطي هذا الرهان الآن.',
    'NETWORK': 'انقطع الاتصال. حاول مرة أخرى.',
    'FAILED': 'حدث خطأ. حاول مرة أخرى.',
    'error': 'تعذر تحميل الطاولة. تحقق من الاتصال.',
  };
}
