class YummyStrings {
  final bool ar;
  const YummyStrings(this.ar);
  String text(String key) => (ar ? _arabic : _english)[key] ?? key;
  String get footer => ar
      ? 'يعمل بعملات سمافوكس — لا تُحوَّل إلى نقود ولا تُسحب.'
      : 'Runs on SamaFox coins — they do not convert to money and cannot be withdrawn.';
  static const _english = {
    'title': 'YUMMY',
    'spin': 'SPIN',
    'stop': 'STOP',
    'bet': 'Bet per line',
    'lines': 'Lines',
    'totalBet': 'Total bet',
    'prize': 'Prize',
    'balance': 'Balance',
    'maximum': 'MAXIMUM BET',
    'settings': 'Settings',
    'help': 'Help & paytable',
    'history': 'History',
    'stats': 'Statistics',
    'sound': 'Sound',
    'motion': 'Motion',
    'language': 'Language',
    'close': 'Close',
    'back': 'Back',
    'retry': 'Try again',
    'loading': 'Loading game…',
    'ready': 'Pick your bet. Ready when you are.',
    'pending': 'Settling your round…',
    'lowBalance': 'Not enough coins for this bet.',
    'error': 'Could not complete the request. Try again.',
    'win': 'WIN',
    'loss': 'LOSS',
    'noWin': 'No prize this round',
    'jackpot': 'JACKPOT',
    'jackpotRule': '1000× bet per winning line',
    'bonus': 'BONUS',
    'pick': 'Choose a chest',
    'bonusRule': 'Your pick reveals the bonus already awarded for this round.',
    'bonusAward': 'Bonus award',
    'clear': 'Clear displayed history',
    'empty': 'No rounds yet',
    'rounds': 'Rounds',
    'wagered': 'Coins played',
    'returned': 'Coins won',
    'net': 'Net result',
    'responsible': 'Play responsibly',
    'responsibleBody':
        'Set a limit, take breaks, and only play with coins you are comfortable spending. A loss does not make the next spin more likely to win.',
    'rules':
        'Match at least 3 adjacent symbols from the leftmost reel on an active line. The best match pays once per line. Multipliers below apply to the bet per line.',
    'wildRule':
        'WILD substitutes regular fruit, candy and diamond symbols only. A run of WILD can pay on its own. WILD never substitutes BONUS or JACKPOT.',
    'bonusHelp':
        '3 or more BONUS anywhere awards 2×, 5× or 10× the total bet. Pick a chest to reveal it; the choice does not change the award.',
    'jackpotHelp':
        '3 or more adjacent crowns from the left on an active line pays 1000× the bet per line. The jackpot label shows that fixed award, not a progressive pool.',
    'stopHelp':
        'STOP ends the animation only. The server has already decided the round. MAXIMUM BET changes the bet and lines without spinning.',
    'caps':
        'Server prize caps apply. The final credited prize is shown separately if a cap reduces a win.',
    'capped': 'Prize reduced by server limits',
    'bigWin': 'BIG WIN',
    'megaWin': 'MEGA WIN',
    'tapToContinue': 'Tap to continue',
    'fairness': 'Fairness',
    'commitment': 'Server seed hash',
    'clientSeed': 'Client seed',
    'nonce': 'Nonce',
    'save': 'Save',
    'rotate': 'Reveal & rotate seed',
    'revealed': 'Retired server seed',
    'verify': 'Verify last round',
    'verified': 'Round matches the revealed seed.',
    'mismatch': 'This seed does not match that round.',
    'fairHelp':
        'The seed hash commits the server before a spin. Rotate to reveal the old seed, then verify a round played with it. Verification reproduces the uncapped prize.',
    'noRound': 'Play a round before verifying.',
    'disabled': 'This game is currently unavailable.',
    'limits': 'Total bet limits',
    'roundCap': 'Maximum round prize',
    'dailyCap': 'Daily prize limit',
    'unlimited': 'No configured cap',
    'decrease': 'Decrease',
    'increase': 'Increase',
    'line': 'Line',
    'strawberry': 'Strawberry',
    'cherry': 'Cherry',
    'orange': 'Orange',
    'lemon': 'Lemon',
    'watermelon': 'Watermelon',
    'grapes': 'Grapes',
    'candy': 'Candy',
    'diamond': 'Diamond',
    'wild': 'Wild',
    'date': 'Date',
    'cleared': 'Displayed history cleared',
    'seedSaved': 'Client seed saved',
  };
  static const _arabic = {
    'title': 'يمي',
    'spin': 'دوران',
    'stop': 'إيقاف',
    'bet': 'الرهان لكل خط',
    'lines': 'الخطوط',
    'totalBet': 'إجمالي الرهان',
    'prize': 'الجائزة',
    'balance': 'الرصيد',
    'maximum': 'أقصى رهان',
    'settings': 'الإعدادات',
    'help': 'المساعدة وجدول الأرباح',
    'history': 'السجل',
    'stats': 'الإحصائيات',
    'sound': 'الصوت',
    'motion': 'الحركة',
    'language': 'اللغة',
    'close': 'إغلاق',
    'back': 'رجوع',
    'retry': 'إعادة المحاولة',
    'loading': 'جارٍ تحميل اللعبة…',
    'ready': 'اختر رهانك وابدأ عندما تكون مستعدًا.',
    'pending': 'جارٍ تسوية الجولة…',
    'lowBalance': 'رصيدك لا يكفي لهذا الرهان.',
    'error': 'تعذر إكمال الطلب. حاول مرة أخرى.',
    'win': 'فوز',
    'loss': 'خسارة',
    'noWin': 'لا توجد جائزة في هذه الجولة',
    'jackpot': 'جاكبوت',
    'jackpotRule': '١٠٠٠ × رهان الخط الفائز',
    'bonus': 'مكافأة',
    'pick': 'اختر صندوقًا',
    'bonusRule': 'اختيارك يكشف المكافأة التي حُسبت بالفعل لهذه الجولة.',
    'bonusAward': 'جائزة المكافأة',
    'clear': 'مسح السجل المعروض',
    'empty': 'لا توجد جولات بعد',
    'rounds': 'الجولات',
    'wagered': 'العملات المستخدمة',
    'returned': 'العملات المكتسبة',
    'net': 'صافي النتيجة',
    'responsible': 'اللعب بمسؤولية',
    'responsibleBody':
        'حدد ميزانيتك وخذ استراحات، والعب فقط بعملات يمكنك إنفاقها. الخسارة لا تزيد احتمال الفوز في الجولة التالية.',
    'rules':
        'اجمع ٣ رموز متطابقة متجاورة أو أكثر بدءًا من البكرة اليسرى على خط نشط. تُحسب أفضل مطابقة مرة واحدة لكل خط. المضاعفات أدناه تُضرب في رهان الخط.',
    'wildRule':
        'الوايلد يحل محل الفواكه والحلوى والماس فقط. سلسلة الوايلد لها جائزة خاصة. لا يحل محل المكافأة أو الجاكبوت.',
    'bonusHelp':
        'ظهور ٣ هدايا أو أكثر في أي مكان يمنح ٢ أو ٥ أو ١٠ أضعاف إجمالي الرهان. اختر صندوقًا لكشفها؛ الاختيار لا يغير المكافأة.',
    'jackpotHelp':
        '٣ تيجان متجاورة أو أكثر بدءًا من اليسار على خط نشط تمنح ١٠٠٠ ضعف رهان الخط. شريط الجاكبوت يعرض هذه الجائزة الثابتة وليس صندوقًا تصاعديًا.',
    'stopHelp':
        'زر الإيقاف ينهي الحركة فقط؛ الخادم حدد نتيجة الجولة بالفعل. أقصى رهان يغير المبلغ والخطوط دون بدء دوران.',
    'caps':
        'تُطبق حدود جوائز الخادم. تظهر الجائزة المقيدة بشكل منفصل عند تخفيض المكسب بسبب أحد الحدود.',
    'capped': 'خُفضت الجائزة وفق حدود الخادم',
    'bigWin': 'فوز كبير',
    'megaWin': 'فوز ضخم',
    'tapToContinue': 'اضغط للمتابعة',
    'fairness': 'العدالة',
    'commitment': 'بصمة بذرة الخادم',
    'clientSeed': 'بذرة اللاعب',
    'nonce': 'رقم الجولة',
    'save': 'حفظ',
    'rotate': 'كشف البذرة وتغييرها',
    'revealed': 'بذرة الخادم السابقة',
    'verify': 'التحقق من آخر جولة',
    'verified': 'الجولة تطابق البذرة المكشوفة.',
    'mismatch': 'هذه البذرة لا تطابق الجولة.',
    'fairHelp':
        'بصمة البذرة تثبت التزام الخادم قبل الدوران. غيّرها لكشف البذرة السابقة ثم تحقق من جولة لُعبت بها. التحقق يعيد الجائزة قبل تطبيق الحدود.',
    'noRound': 'العب جولة أولًا للتحقق.',
    'disabled': 'اللعبة غير متاحة حاليًا.',
    'limits': 'حدود إجمالي الرهان',
    'roundCap': 'أقصى جائزة للجولة',
    'dailyCap': 'حد الجوائز اليومي',
    'unlimited': 'لا يوجد حد محدد',
    'decrease': 'تقليل',
    'increase': 'زيادة',
    'line': 'خط',
    'strawberry': 'فراولة',
    'cherry': 'كرز',
    'orange': 'برتقال',
    'lemon': 'ليمون',
    'watermelon': 'بطيخ',
    'grapes': 'عنب',
    'candy': 'حلوى',
    'diamond': 'ماس',
    'wild': 'وايلد',
    'date': 'التاريخ',
    'cleared': 'تم مسح السجل المعروض',
    'seedSaved': 'تم حفظ بذرة اللاعب',
  };
}
